DROP TABLE IF EXISTS Carrito;
DROP TABLE IF EXISTS Envia;
DROP TABLE IF EXISTS Postea;
DROP TABLE IF EXISTS Compra;
DROP TABLE IF EXISTS Formulario;
DROP TABLE IF EXISTS Articulo;
DROP TABLE IF EXISTS Usuario;